on:
  workflow_dispatch:
jobs:
  job_1:
    stratey:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.X, 16.X, 18.X]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix['node-version'] }}